# Install script for directory: D:/FreeRdpClient/FreeRDP-master/winpr/libwinpr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files/FreeRDP")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "libraries")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "D:/FreeRdpClient/Debug/winpr.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "D:/FreeRdpClient/Release/winpr.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "D:/FreeRdpClient/MinSizeRel/winpr.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY OPTIONAL FILES "D:/FreeRdpClient/RelWithDebInfo/winpr.lib")
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "libraries")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "D:/FreeRdpClient/Debug/winpr.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "D:/FreeRdpClient/Release/winpr.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "D:/FreeRdpClient/MinSizeRel/winpr.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "D:/FreeRdpClient/RelWithDebInfo/winpr.dll")
  endif()
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("D:/FreeRdpClient/winpr/libwinpr/synch/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/locale/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/library/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/file/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/comm/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/pipe/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/interlocked/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/security/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/environment/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/crypto/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/registry/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/credentials/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/path/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/io/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/memory/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/input/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/shell/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/heap/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/utils/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/error/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/com/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/timezone/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/sysinfo/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/pool/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/handle/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/thread/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/winsock/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/sspi/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/winhttp/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/asn1/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/sspicli/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/crt/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/bcrypt/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/rpc/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/credui/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/wtsapi/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/dsparse/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/wnd/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/smartcard/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/nt/cmake_install.cmake")
  include("D:/FreeRdpClient/winpr/libwinpr/clipboard/cmake_install.cmake")

endif()

